#  Numpy 설치하기

`pip install numpy`
 

**주의!** `pip freeze > requirements.txt` 로 라이브러리 업데이트 하기

# Array 생성하기

In [1]:
import numpy as np

In [4]:
d1 = np.array([1, 2, 3]) # [1, 2, 3]
d1

array([1, 2, 3])

In [5]:
d2 = np.array([[1, 2, 3], [4, 5, 6]])
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])