#  Numpy 설치하기

`pip install numpy`
 

**주의!** `pip freeze > requirements.txt` 로 라이브러리 업데이트 하기

# Array 생성하기

In [1]:
import numpy as np

In [2]:
d1 = np.array([1, 2, 3]) # [1, 2, 3]
d1

array([1, 2, 3])

In [3]:
d2 = np.array([[1, 2, 3], [4, 5, 6]])
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

# Numpy 다루기

## array 확인하기

In [7]:
d2_zeros = np.zeros((5, 5))
d2_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
d2_zeros.shape

(5, 5)

In [9]:
len(d2_zeros)

5

In [10]:
d2_zeros.size

25

## array 계산하기 

In [11]:
d1_a = np.array([9, 8, 7])
d1_b = np.array([1, 2, 3])

In [12]:
d1_a + d1_b

array([10, 10, 10])

In [13]:
d1_a - d1_b

array([8, 6, 4])

In [14]:
d1_a * d1_b

array([ 9, 16, 21])

In [15]:
d1_a / d1_b

array([9.        , 4.        , 2.33333333])

In [16]:
# 사이즈가 다르면?
# np.array([1, 2, 3, 4, 5]) - d1_a # [9, 8, 7]

In [17]:
d1_a.sum()

24

In [18]:
d1_a.min()

7

In [19]:
d1_a.max()

9

In [20]:
d1_a.mean()

8.0

In [21]:
np.median(d1_a)

8.0

In [22]:
np.corrcoef(d1_a, d1_b)

array([[ 1., -1.],
       [-1.,  1.]])

# 파일 다루기

In [23]:
f = np.genfromtxt("./international_football_results.csv", delimiter=",", names=True, dtype=None, encoding='UTF8')

In [24]:
print(f)

[('1872-11-30', 'Scotland', 'England', 0, 0, 'Friendly', 'Glasgow', 'Scotland', False)
 ('1873-03-08', 'England', 'Scotland', 4, 2, 'Friendly', 'London', 'England', False)
 ('1874-03-07', 'Scotland', 'England', 2, 1, 'Friendly', 'Glasgow', 'Scotland', False)
 ...
 ('2018-07-07', 'Sweden', 'England', 0, 2, 'FIFA World Cup', 'Samara', 'Russia',  True)
 ('2018-07-07', 'Russia', 'Croatia', 2, 2, 'FIFA World Cup', 'Sochi', 'Russia', False)
 ('2018-07-10', 'France', 'Belgium', 1, 0, 'FIFA World Cup', 'St. Petersburg', 'Russia',  True)]


In [25]:
f.shape

(39669,)

In [26]:
date = np.array(list(map(lambda x: x[0], f)))
score = np.array(list(map(lambda x: x[3], f)))

In [27]:
print(date)

['1872-11-30' '1873-03-08' '1874-03-07' ... '2018-07-07' '2018-07-07'
 '2018-07-10']


In [28]:
print(score)

[0 4 2 ... 0 2 1]
